# Introduction

In November of 2019, the Utah Transit Authority (UTA) began a partnership with VIA, a private mobility company. Under this partnership, UTA has supplemented its fixed-route services in south Salt Lake County with on-demand shuttles hailed through a mobile application. On-demand transit (ODT) offerings of this kind have the potential to efficiently extend UTA services into low-density areas and function as last-mile services for the regular fixed-route rail and bus network. UTA is interested in examining other areas where microtransit services can be effectively deployed.

In September 2020, UTA released a report detailing a possible expansion of ODT services to other areas in Utah following the UTA on Demand pilot program [@UTAreport]. 19 zones were identified between Brigham City and Santaquin as areas that could potentially benefit from these services. VIA estimated ODT ridership based on number of residents and number of workers employed within each zone, as well as a mode share score that VIA developed based on their internal demand model. This model, however, has several limitations. The model itself is proprietary, and VIA gave little indication as to its mechanisms for predicting ridership. Although, from the information that _is_ provided, we believe it to be a type of regression model or something similar. As such, we have no way of knowing if VIA's model is appropriate for the areas studied.

In this report, we present an alternative method of forecasting ODT ridership. We use the Behavior, Energy, Autonomy, and Mobility (BEAM) model developed by Lawrence Berkeley National Laboratory to directly simulate transportation demand, including mode choice. BEAM operates on an agent-based level, simulating individual agents and vehicles traversing a given network based on dynamically calculated parameters such as congested travel times. With this model, we seek to provide a better analysis method for existing and potential ODT services.

This research takes the BEAM model as given, modifying only those parameters and implementations that are necessary to conduct the current analysis. For example, we will modify the BEAM code to enable geo-fenced microtransit operations, which are a critical component of the current research. We will not attempt to modify BEAM’s multi-modal pathfinding algorithms, which may affect the current research but must be taken as given under the scope of this project.

The primary objective of this research project is to identify possible geographic areas along the Wasatch Front where an ODT system might most effectively operate, while a secondary objective of this research will be to provide a template for UDOT and UTA to examine projects of this kind with a microsimulation model. Utah has invested a great deal of resources into fixed route, high-capacity transit lines such as UVX, TRAX, and FrontRunner. These services perform well and have relatively high ridership statistics, but many people not directly near the stations can have difficulty accessing them. UTA will use this research to identify other places on the Wasatch Front where microtransit offerings could be successful. UDOT could also use this methodology to study the potential effectiveness of such services in other areas, such as Logan, Moab, and Cedar City.

## Outline of Report

The report is organized into the following chapters:

1. **Introduction:** This chapter.
2. **Literature Review:** An overview of previous efforts to understand microtransit systems and forecast their operations.
3. **Methodology:** Methods and data used to create the initial microsimulation scenario in the Salt Lake City region.
4. **Results:** A comparison of initial BEAM modeling to observed data, and an evaluation of three additional regions selected by UTA and UDOT for simulation analysis.
5. **Recommendations and Conclusions**
