# Literature Review

## Overview

This chapter presents prior attempts in the academic and practical literature to understand, model, and predict ridership for on-demand transit systems. The literature highlights the power and flexibility of demand-based modeling. MATSim is an agent-based simulation that models individuals’ behavior, and BEAM (an extension to MATSim) places even more focus on individuals. As our project deals with modeling the UTA on Demand by VIA pilot program in Salt Lake City, we additionally discuss the program and the results it has achieved so far. Ultimately, we conclude that we will be using BEAM to model this and other potential on-demand transit implementations.


## Purposes and Description of On-Demand Transit

One aspect of traditional public transit is that the routes are usually fixed. It is not always feasible to extend these fixed-route systems into less densely populated areas (at least, not in a way that would reasonably service most of the residents) due to the high costs of capital and operation and the relatively low ridership that would result [@MinetaTransportationInstitute2012]. However, public transit has many benefits such as reduced carbon emissions per person-mile and less traffic congestion [@Buchanan2019; @Gershon2005], and the lack of transit options in many suburban areas requires residents to overwhelmingly use personal vehicles as their main form of transportation [@Gershon2005]. This raises the question of the most effective and efficient way to increase transit ridership and decrease dependence on personal vehicles in these areas.

One possible solution is the introduction of microtransit services. Microtransit is a form of shared, on-demand transportation (ODT) in which passengers schedule rides and vehicle routing is updated in real time to efficiently transport its users. The vehicles used are usually a form of minibus that can hold several passengers at once [@Shaheen2015]. One key application of microtransit is for first- and last-mile transportation, connecting a wide area to the existing fixed-route network [@Shaheen2015] and taking less time than walking or cycling. Decreasing this first/last mile travel time can increase job accessibility by allowing individuals to travel farther with the same travel time budget, and some microtransit services have been shown to decrease this time significantly [@Kang2019]. Especially as smartphone ownership and usage continues to increase, microtransit is a promising option, as booking rides can be done within phone apps, making the user experience easier [@Agatz2011].

### Analysis framework

@Alonso-Gonzalez2018 set out to create an analysis framework that can be used to evaluate ODT services, both in simulation and real-world application, in order to compare them to existing systems. The framework presented requires identifying several characteristics of the ODT system: coverage and routing, operating hours, vehicle characteristics, the booking system, and request acceptance criteria. Then several quantities are calculated or estimated, including generalized journey time and share of declined ODT trips as well as usage values. The ODT system is then compared with other modes such as fixed transit and walking/biking. The study concludes that a generalized cost of travel metric would be the most useful in comparing the ODT system against other options, as it was a good indicator of changes in mobility.


## Previous Attempts to Model On-Demand Transit

Due to the high potential of ODT/microtransit services, many models and simulations have been created. @Vosooghi2017 published a literature review discussing several simulation software packages: @Azevedo2016 used SimMobility to model an autonomous taxi network, MobiTroop was used by @Heilig2015 to simulate carsharing in the Stuttgart, Germany area, and MATSim has been used to develop a carsharing model in Berlin [@Ciari2014] and analyze one in Zurich [@Balac2015], and it was used to model a shared autonomous vehicle system [@Fagnant2014].

@Ronald2015 looked at three software simulations in more detail: the basic simulation Delphi, the agent-based simulation MATSim, and the traffic microsimulation SUMOoD (SUMO on Demand). The study found that these simulations generally produced similar results with respect to number of vehicles and amount of demand, and noted that all simulations performed as expected based on real-world observations [@Schofer2003]. They are also quick to point out that results of these simulations might be optimistic if simplifications to routing are made or if using an undirected network, where a vehicle could pick up passengers on either side of a road no matter the direction of travel.

### MATSim and BEAM

MATSim (Multi-Agent Transport Simulation) is an open-source framework for transportation modeling originally developed in Zurich. The framework simulates traffic flows and congestion on a microscopic level, and simulates demand by creating agents and following their daily schedules and decisions. It is designed to model a single day in large-scale scenarios, and uses an iterative process to have each agent optimize their schedule and consider factors such as route choice, mode choice, time choice, and destination choice [@Horni2016]. This is similar to how many people would likely use a transportation network: either trying several options and sticking with what works best for them, or using a routing service (such as Google Maps) to find their optimal route. It is important to note that this is different than finding the optimal solution for the whole system (which likely would lead to some agents individually being assigned very poor routing/mode choice/etc.); each individual tries to optimize their own travel, and MATSim outputs the overall equilibrium that results [@Horni2016]. MATSim has been used in numerous studies to model various scenarios: @Bischoff2016 simulated a city-wide replacement of personal vehicles with autonomous taxis in Berlin, @Cyganski2018 introduced autonomous vehicles and ODT to Brunswick via simulation, and @Viergutz2019 modeled ODT vs public transit in the rural town of Colditz.

BEAM, which stands for Behavior, Energy, Autonomy, and Mobility, is an extension to the MATSim framework, and is maintained by Lawrence Berkeley National Laboratory [@BEAMlbnl]. The BEAM documentation [@beamdocs] gives a description of some of its functions and purposes. The simulation is designed to simplify running full-scale transportation models, and places an emphasis on within-day agent mode choice and planning (as an example, after an agent requests a ODT vehicle, they may decide the wait time is too long and choose another mode). It is also intended to find the equilibrium point where resource markets (including road capacity and fleet availability) match the demand for service.


## Real-World Microtransit

Microtransit/ODT has generally performed well in simulations; however, few ODT services have been implemented in the real world. Perhaps the most notable is Kutsuplus, which was implemented in Helsinki, Finland from 2012–2015. An official report of the system was created, but did not include an analysis regarding the mobility improvements compared with already-existing alternatives [@Gonzalez2018; @Kari2016].

### UTA On Demand by VIA

Another real-world microtransit implementation began in November 2019, when Utah Transit Authority (UTA) partnered with VIA to run a pilot microtransit service, UTA on Demand, in southern Salt Lake County [@UTAreport]. The two main goals of this program were to expand access to public transit, providing first- and last-mile connections, and increase mobility for all users, even on trips not involving fixed-route transit. The purpose of the pilot program was to determine if microtransit would achieve these goals effectively [@UTAevalDEC].

As of the time of writing, monthly reports on the program are available from December 2019 through November 2020, as well as four quarterly reports. Several metrics were measured and compared to previously set goals in different areas, such as ridership, wait times, and cost per rider. At the end of the first quarter (December–February), the pilot program either met or was on track to meet the 6-month goals for each metric [@UTAevalQ1]. However, due to the COVID-19 pandemic becoming prevalent in Utah beginning mid-March, significantly fewer people have utilized the service since then, and average ridership from March through November was significantly lower than the 6-month goals [@UTAevalQ3].

Though the pilot program did not meet the goals that were originally set, UTA renewed its contract with VIA for an additional year [@UTAevalQ3]. This is in part because the program was projected to have met its 6-month goals in absence of the pandemic [@UTAevalQ2], and also more generally for continued evaluation and testing [@UTAevalQ3].

In September 2020, UTA released a report detailing a possible expansion of microtransit services to other areas in Utah following the UTA on Demand pilot program [@UTAreport]. Three characteristics were considered: Transit potential, reflecting population and employment density; transit need, reflecting socio-economic factors that indicate a higher propensity to use transit; and the existing transit service level, based on quality and quantity of transit already available in the area. Based on these characteristics, 19 zones were identified between Brigham City and Santaquin as areas that could potentially benefit from microtransit services. Ridership was estimated based on number of residents and number of workers employed within each zone, as well as a mode share score that VIA developed based on their internal demand model. The report makes no definitive recommendation regarding expanding microtransit services, but does present several results of the analysis for each zone, including how well microtransit would improve transit coverage, provide efficient transit, replace existing bus routes, and increase equity. The report also notes several considerations regarding accessibility (including paratransit) and operations, and that this study will inform UTA’s future transit choices.


## Summary

Many different transportation simulation packages have been created and used in various situations. Part of this project involves developing a model that UTA can use for future research. Much of this work has been done previously in another UDOT-sponsored research project in developing a simulation including wheelchair-accessible microtransit vehicles. That project uses BEAM to develop its model, as BEAM effectively models individual user behavior in full-scale simulations. Because of this, we will be using BEAM as well in our research.
