# Candidate Region Evaluation

## Overview

We created several scenarios with microtransit fleets in various areas. A map of these areas is given below:

```{r load_shapefiles}
# TODO: move to targets pipeline
SLCSouth <- read_sf("data/Zones/SLCSouth/SLCSouth_polygon.shp") %>% st_transform(crs = 3857)
Airport <- read_sf("data/Zones/WestCity/WestCity_polygon.shp") %>% st_transform(crs = 3857)
Sandy <- read_sf("data/Zones/Sandy/Sandy_polygon.shp") %>% st_transform(crs = 3857)
Jordan <- read_sf("data/Zones/WestJordan/WestJordan_polygon.shp") %>% st_transform(crs = 3857)
```

```{r map, fig.cap="Ridehail zones in Salt Lake County."}
# TODO: move to targets pipeline
pal <- wesanderson::wes_palette("Moonrise2")
colors <- c("SLCSouth" = pal[1],
            "Airport" = pal[2],
            "Sandy" = pal[3],
            "West Jordan" = pal[4])
ggplot() + 
  annotation_map_tile("cartolight", zoom = 12) + 
  coord_sf(crs = 3857) +
  geom_sf(data = Airport, aes(fill = "Airport"), inherit.aes = F, alpha = 0.8) +
  geom_sf(data = Sandy, aes(fill = "Sandy"), inherit.aes = F, alpha = 0.8) +
  geom_sf(data = Jordan, aes(fill = "West Jordan"), inherit.aes = F, alpha = 0.8) +
  geom_sf(data = SLCSouth, aes(fill = "SLCSouth"), inherit.aes = F, alpha = 0.8) +
  theme_map() +
  scale_fill_manual(name = "Zones", values = colors)
```

```{r areas-map}
# tar_load(areas)
# pal <- wes_palette("Zissou1", 6, type = "continuous")
# if(knitr::is_html_output()){
#   # interactive map for web
#   leaflet(areas %>% st_transform(4326)) %>%
#     addProviderTiles(providers$CartoDB) %>%
#     addPolygons(label = ~name, color = pal)
# } else {
#   # static map for pdf
#   ggplot(areas, aes(fill = name)) + 
#     annotation_map_tile("cartolight", zoom = 12) +
#     geom_sf(alpha = 0.5) +
#     scale_fill_manual("Area Name", values = pal) + 
#     theme(
#       axis.text.x=element_blank(),
#       axis.text.y=element_blank(),axis.ticks=element_blank(),
#       axis.title.x=element_blank(),
#       axis.title.y=element_blank(),
#       legend.text=element_text(size=8), #change font size of legend text
#       legend.title=element_text(size=8)
#     )
# }
```
The combinations of areas in each scenario is given:

TODO: add and reference that file here (it exists, just not in this repo yet)

And the results of our simulations:

```{r}
tar_make(all_comparisons)

tar_read(all_comparisons)
```



## Summary

Other, more different text
